require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0
  TargetRailsVersion: 7.0
  NewCops: enable
  Exclude:
    - "**/db/migrate/*"
    - "db/schema.rb"
    - "**/Gemfile.lock"

Style/Documentation:
  Enabled: false
